# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e54ec898f7556c5229b0256307ba9c162dffbce447aac1e91475b39fd7e08a56a662040cd1f4c7b2fa46aeeb6d4192a48581642d0792a17d1ac8d1fa3132b54

test:
  secret_key_base: 046a1f738259e61368c958121e10d9c7e00320e2f62d5bfd26b55d20a07e4d55dcc9aaf8e5bc29e242ba0c3b044f568be542e383b35340db1b0366c10b76c188

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
